#!/bin/sh
# Git config
git config --global alias.ad add
git config --global alias.br branch
git config --global alias.co checkout
git config --global alias.ci commit
git config --global alias.df diff
git config --global alias.ft fetch
git config --global alias.last "log -1 HEAD"
git config --global alias.st status
git config --global alias.unstage "reset HEAD --"
git config --global alias.graphlong "log --graph"
git config --global alias.graph "log --graph --oneline"
git config --global color.ui true
git config --global color.diff true
git config --global core.editor 'vim -c "set fenc=utf-8"'
git config --global core.excludesfile "~/.gitignore"
git config --global merge.ff false
git config --global log.decorate true
git config --global log.date relative
# refs: http://yuroyoro.hatenablog.com/entry/20101008/1286531851
git config --global alias.dc "diff --cached"
git config --global alias.ds "diff --staged"
git config --global alias.dm "diff master"
git config --global alias.la "log --pretty=\"format:%ad %h (%an): %s\" --date=short"
git config --global alias.lp "log -p"
git config --global alias.ls "log --stat"
git config --global alias.edit-unmerged "!f() { git ls-files --unmerged | cut -f2 | sort -u ; }; vim \`f\`"
git config --global alias.add-unmerged "!f() { git ls-files --unmerged | cut -f2 | sort -u ; }; git add \`f\`"
git config --global alias.log-graph "log --graph --date=short --pretty=format:'%Cgreen%h %cd %Cblue%cn %Creset%s'"
git config --global alias.log-all "log --graph --all --color --pretty='%x09%h %cn%x09%s %Cred%d%Creset'"
git config --global color.branch true
git config --global color.grep true
git config --global color.interactive true
git config --global color.status true
# Enable auto --rebase when pull action in specify branches
git config --global branch.master.rebase true
git config --global branch.develop.rebase true
if ! type "diff-so-fancy" > /dev/null; then
	if type "npm" > /dev/null; then
		npm install -g diff-so-fancy
	elif type "brew" > /dev/null; then
		brew update
		brew install diff-so-fancy
	fi
	git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"
fi

