#!/bin/sh

DEST=`dirname ${0}`
cd ~
if [ ! -e ~/.zshrc ]; then
	ln -s $DEST/.zshrc ~/.zshrc
elif [ ! -L ~/.zshrc ]; then
	echo "Replace .zshrc for dotfiles"
	mv ~/.zshrc ~/.zshrc.old
	ln -s $DEST/.zshrc ~/.zshrc
fi
if [ ! -e ~/.vimrc ]; then
	ln -s $DEST/.vimrc ~/.vimrc
elif [ ! -L ~/.vimrc ]; then
	echo "Replace .vimrc for dotfiles"
	mv ~/.vimrc ~/.vimrc.old
	ln -s $DEST/.vimrc ~/.vimrc
fi
if [ ! -e ~/.gemrc ]; then
	ln -s $DEST/.gemrc ~/.gemrc
elif [ ! -L ~/.gemrc ]; then
	echo "Replace .gemrc for dotfiles"
	mv ~/.gemrc ~/.gemrc.old
	ln -s $DEST/.gemrc ~/.gemrc
fi
if [ ! -e ~/.tmux.conf ]; then
	ln -s $DEST/.tmux.conf ~/.tmux.conf
elif [ ! -L ~/.tmux.conf ]; then
	echo "Replace .tmux.conf for dotfiles"
	mv ~/.tmux.conf ~/.tmux.conf.old
	ln -s $DEST/.tmux.conf ~/.tmux.conf
fi


# Environment of NeoBundle for Vim
if [ ! -e ~/.vim ]; then
   echo "No ~/.vim directory detected."
   mkdir -p ~/.vim/bundle
   echo "~/.vim directory created."
fi
if [ ! -e ~/.vim/bundle/neobundle.vim ]; then
   echo "No 'NeoBundle' for Vim plugin detected."
   echo "Installing NeoBundle..."
   git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
   vim +NeoBundleInstall +q
fi


# Install rbenv
if [ ! -e ~/.rbenv ]; then
	echo "Installing rbenv..."
	git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
	git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
	export PATH="$HOME/.rbenv/bin:$PATH"
	eval $(rbenv init -)
	rbenv install 2.0.0-p247
	rebenv rehash
	rbenv local 2.0.0-p247
	rbenv global 2.0.0-p247
fi

# Install nvm
if [ ! -e ~/.nvm ]; then
	curl https://raw.github.com/creationix/nvm/master/install.sh | sh
	source ~/.nvm/nvm.sh
fi

# Install nodebrew
#if [ ! -e ~/.nodebrew ]; then
#	curl https://raw.github.com/hokaccha/nodebrew/master/nodebrew | perl - setup
#	export PATH=$HOME/.nodebrew/current/bin:$PATH
#	nodebrew install-binary v0.10.12
#	nodebrew use v0.10.12
#fi



